# Generated by Django 3.0.1 on 2020-07-18 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_auto_20200718_0705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='degree',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='dob',
            field=models.DateField(help_text='yyyy-mm-dd', verbose_name='Date of Birth'),
        ),
    ]
