# Generated by Django 3.0.1 on 2020-07-19 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_auto_20200718_0721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='profile_pic',
            field=models.ImageField(default="{% static 'accounts/default.jpg' %}", upload_to='profile_pics'),
        ),
    ]
