# Generated by Django 3.0.1 on 2020-07-19 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_auto_20200719_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='profile_pic',
            field=models.ImageField(default='static/default.jpg', upload_to='profile_pics'),
        ),
    ]
